# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Digidoc4j CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  digidoc4j_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
        java: [ 8, 11, 15 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn clean verify -q -"Dgpg.skip"
